on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters
    steps:
      - uses: actions/checkout@v2 
      - run: make check
  build:
    runs-on: ubuntu-latest
    container: kubaj/cmake-valgrind
    needs: [check]
    steps:
    - uses: actions/checkout@v2 
    - run: make build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: server
  memtest:
    runs-on: ubuntu-latest
    container: kubaj/cmake-valgrind
    needs: [build]
    steps:
      - uses: actions/checkout@v2 
      - run: make memtest