on: push

jobs:
  check:
    runs-on: ubuntu-latest
    # container: leshiy1295/gcc_linters_valgrind_cmake_gtest
    steps:
      - uses: actions/checkout@v2 
      - run: |
          docker build . -t app
          docker -it -v $PWD:/home app cd home & make check

  build:
    runs-on: ubuntu-latest
    # container: leshiy1295/gcc_linters_valgrind_cmake_gtest
    needs: [check]
    steps:
    - uses: actions/checkout@v2 
    - run: make build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: server

  memtest:
    runs-on: ubuntu-latest
    # container: leshiy1295/gcc_linters_valgrind_cmake_gtest
    needs: [build]
    steps:
      - uses: actions/checkout@v2 
      - run: |
          apt install -y lcov
          make memtest 
